[package]
name = "the-watchers-rust"
version = "0.2.5"
edition = "2021"

[dependencies]
chrono = "0.4.40"
rand = "0.9.1"
ratatui = "0.29.0"
tokio = { version = "1.44.2", features = ["full"] }

[[bin]]
name = "the-watchers-rust"
path = "src/main.rs"
