# For content authors -- people adding `.being` entity files.
#
# Run:  powershell -File scripts\tests-content.ps1
# Reads: tests\safety_being.rs
# Writes: docs\tests\content-authors.md  (read this; you don't need to run anything)

. "$PSScriptRoot\_catalog.ps1"

$cat = Get-TestCatalog (Get-TestFiles 'safety_being.rs')

$md = @()
$md += '# The `.being` safety contract'
$md += ''
$md += 'What no content file can break. Every `.being` is authored by anyone, so'
$md += 'the engine promises these guarantees hold for *any* bytes you put in a file.'
$md += 'Each line below is one such promise, taken straight from a test.'
$md += ''
$md += '> Generated by `scripts\tests-content.ps1`. Do not edit by hand -- edit the tests.'

foreach ($f in $cat) {
    $md += ''
    foreach ($t in $f.Tests) {
        $md += "- $($t.Sentence)"
    }
}

Save-Catalog 'docs\tests\content-authors.md' $md
