# For reviewers -- audit each test's truthfulness.
#
# Run:  powershell -File scripts\tests-reviewers.ps1
# Reads: every tests\*.rs
# Writes: docs\tests\reviewers.md  (read this; you don't need to run anything)
#
# Shows what each test *says* (its name) next to *why* it exists (its `///`).
# If the two disagree, the test is lying -- that is the thing to catch.

. "$PSScriptRoot\_catalog.ps1"

$repo  = Split-Path -Parent $PSScriptRoot
$files = Get-ChildItem -Path (Join-Path $repo 'tests') -Filter '*.rs' | ForEach-Object { $_.FullName }
$cat   = Get-TestCatalog $files

$md = @()
$md += '# Test review sheet'
$md += ''
$md += 'Each test, what it claims, and the rationale written above it. Read the two'
$md += 'together: if the name promises more (or less) than the rationale, flag it.'
$md += ''
$md += '> Generated by `scripts\tests-reviewers.ps1`. Do not edit by hand -- edit the tests.'

foreach ($f in $cat) {
    $md += ''
    $md += "## $($f.File)"
    foreach ($t in $f.Tests) {
        $md += ''
        $md += "### ``$($t.Name)``"
        $md += "**Says:** $($t.Sentence)"
        $md += ''
        if ($t.Rationale) { $md += "**Rationale:** $($t.Rationale)" }
        else              { $md += '**Rationale:** _(none -- a test with no stated reason is worth a look)_' }
    }
}

Save-Catalog 'docs\tests\reviewers.md' $md
