# For new contributors -- the whole map, friendly.
#
# Run:  powershell -File scripts\tests-contributors.ps1
# Reads: every tests\*.rs
# Writes: docs\tests\contributors.md  (read this; you don't need to run anything)

. "$PSScriptRoot\_catalog.ps1"

$repo  = Split-Path -Parent $PSScriptRoot
$files = Get-ChildItem -Path (Join-Path $repo 'tests') -Filter '*.rs' | ForEach-Object { $_.FullName }
$cat   = Get-TestCatalog $files

$md = @()
$md += '# Test catalog -- the guarantees'
$md += ''
$md += 'The test suite, read as plain sentences. Each test is one promise the engine'
$md += 'keeps; a red one means a promise was lost. Grouped by file.'
$md += ''
$md += '> Generated by `scripts\tests-contributors.ps1`. Do not edit by hand -- edit the tests.'

foreach ($f in $cat) {
    # First sentence of the module header gives the section its gist.
    $gist = ($f.Header -split '(?<=\.)\s')[0]
    $md += ''
    $md += "## $($f.File)"
    if ($gist) { $md += ''; $md += "_${gist}_" }
    $md += ''
    foreach ($t in $f.Tests) {
        $md += "- $($t.Sentence)"
    }
}

Save-Catalog 'docs\tests\contributors.md' $md
